// hel_react/src/App.jsx
import {useRef, useState} from 'react';
import MyInput from "./MyInput.jsx";

function App() {
    const [obj, setObj] = useState("HAAHAHA");
    const [obj_value, setObj_value] = useState("LALALALAL");

    const myclick = () => {
        setObj("GOGOGGOGOO");
        setObj_value("NONONONONOO");
    }

    return (
        <>
            <input type="text"  value={obj}/>
            <MyInput value={obj_value} />
            <button onClick={myclick}>Uraraaa</button>
        </>

    );
}

export default App;

// hel_vue/src/App.vue
<script setup>
import { ref } from 'vue'
import MyInput from "./components/MyInput.vue";

let obj = ref(null);
let obj_value =ref(null);

const myclick= () => {
  obj.value.value= "bye"
  obj_value.value.setValue("bye");
}

</script>

<template>
  <input type="text" value="hello" ref="obj"/><br/>
  <MyInput value="hallo" ref="obj_value"/><br/>
  <button @click="myclick">CHANGE TEXT</button><br/>
</template>
