// hel_vue/src/App.vue
<script setup>
import { ref } from 'vue'
import MyInput from "./components/MyInput.vue";

let obj = ref(null);
let obj_value =ref(null);

const myclick= () => {
  obj.value.value= "bye"
  obj_value.value.setValue("bye");
}

</script>

<template>
  <input type="text" value="hello" ref="obj"/><br/>
  <MyInput value="hallo" ref="obj_value"/><br/>
  <button @click="myclick">CHANGE TEXT</button><br/>
</template>

// hel_svelte/src/App.svelte
<script>
  import MyInput from "./lib/MyInput.svelte";
  let obj = null;
  let mvalue = "Hello Mother Fxxker";

  const myclick = () => {
    obj.value = "Good bye";
    mvalue = "No thanks";  // 반응형으로 업데이트
  }
</script>

<main>
  <input type="text" value="Hello Mother Fxxker" bind:this={obj}/><br/>
  <MyInput bind:value={mvalue} /><br/>
  <button onclick={myclick}>Change Text</button>
</main>
