// hel_vue/src/components/Lotto.vue
<script setup>
import {ref} from 'vue'

let lottNumbers = ref([0, 0, 0, 0, 0, 0])

const myclick = () => {
  let lottArr = [];

  while(lottArr.length < 6){
    let lottNumber = Math.floor(Math.random()*45) + 1;

    if(!lottArr.includes(lottNumber)){
      lottArr.push(lottNumber);
    }
  }
  // lottArr.sort((a,b) => a-b);
  bubbleSort(lottArr);

  function bubbleSort(arr) {
    let temp = 0;
    for(let i = 0; i < arr.length - 1; i++){
      for(let j = 1; j < arr.length - i; j++){
        if(arr[j] < arr[j-1]) {
          temp = arr[j-1];
          arr[j-1] = arr[j];
          arr[j] = temp;
        }
      }
    }
    return arr;
  }

  console.log(lottArr);

  lottNumbers.value = lottArr;
}
</script>

<template>
  <table>
    <tbody>
    <tr>
      <!-- v-for 사용 (key는 필수) -->
      <td v-for="(number, index) in lottNumbers" :key="index">
        <span class="myspan">{{ number || '_' }}</span>
      </td>
    </tr>
    <tr>
      <td colspan="6">
        <button @click="myclick">로또생성하기</button>
      </td>
    </tr>
    </tbody>
  </table>
</template>

<style scoped>
table, tr, td{
  border: 1px solid grey;
}
</style>

// hel_react/src/Lotto.jsx
import { useState } from 'react'
import "./Lotto.css"

function Lotto() {
    // useState로 상태 관리 (React의 핵심!)
    const [lottNumbers, setLottNumbers] = useState([0, 0, 0, 0, 0, 0]);

    const myclick = () => {
        let lottArr = [];

        while (lottArr.length < 6) {
            let lottNumber = Math.floor(Math.random() * 45) + 1;

            if (!lottArr.includes(lottNumber)) {
                lottArr.push(lottNumber);
            }
        }

        // bubbleSort 함수
        function bubbleSort(arr) {
            let temp = 0;
            for (let i = 0; i < arr.length - 1; i++) {
                for (let j = 1; j < arr.length - i; j++) {
                    if (arr[j] < arr[j - 1]) {
                        temp = arr[j - 1];
                        arr[j - 1] = arr[j];
                        arr[j] = temp;
                    }
                }
            }
            return arr;
        }

        bubbleSort(lottArr);
        console.log(lottArr);

        // setState로 상태 업데이트
        setLottNumbers(lottArr);
    }

    return (
        <table>
            <tbody>
            <tr>
                {/* React에서는 map 사용 */}
                {lottNumbers.map((number, index) => (
                    <td key={index}>
                        <span className="myspan">{number || '_'}</span>
                    </td>
                ))}
            </tr>
            <tr>
                <td colSpan="6">
                    <button onClick={myclick}>
                        로또생성하기
                    </button>
                </td>
            </tr>
            </tbody>
        </table>
    )
}

export default Lotto;
