// he_mvvm_vue/src/components/Mem.vue
<script setup>
import {onMounted, ref} from 'vue'
import axios from 'axios'


/*const list = ref([
     {'m_id': '1', 'm_name': '1', 'tel': '1', 'email': '1'},
     {'m_id': '2', 'm_name': '2', 'tel': '2', 'email': '2'},
     {'m_id': '3', 'm_name': '3', 'tel': '3', 'email': '3'}
])*/
const list = ref([])


onMounted(() => {
  fn_list() // 컴포넌트 로드 시 회원 리스트를 불러오는 함수를 호출합니다.
})

const vo = ref({'m_id': "", 'm_name': "", 'tel': "", 'email': ""})


const fn_list = async () => {

  const resp = await axios.get('http://localhost:8080/api/mem_list.ajax')
  list.value = resp.data
}

const fn_one = (m_id) => {
  console.log("fn_one() / m_id => ", m_id);
  axios.get(`http://localhost:8080/api/mem_detail?m_id=${m_id}`)
      .then(res => {
        vo.value = res.data;
        console.log("fn_one(m_id)/res : ", vo.value)
      })
}

const fn_add = async () => {
  if (!vo.value.m_id) {
    alert("사번을 입력해주세요.");
    return;
  }

  if (list.value.some(mem => mem.m_id === vo.value.m_id)) {
    alert("이미 있는 사번입니다.");
    return;
  }

  const resp = await axios.post('http://localhost:8080/api/mem_add', vo.value);
  console.log("추가 결과", resp.data)
  if (resp.data === 1) {
    alert("추가 완료!");
  } else {
    alert("추가 실패!");
  }
  fn_clear();
  await fn_list()
}
const fn_mod = async () => {

  const resp = await axios.post('http://localhost:8080/api/mem_mod', vo.value);
  if (resp.data === 1) {
    alert("수정 완료!");
  } else {
    alert("수정 실패!");
  }
  fn_clear()
  await fn_list()
}

const fn_del = async () => {
  if (confirm("한번 지워진 데이터는 복구 불가능합니다.\n정말 삭제하겠습니까?")) {
    const resp = await axios.post('http://localhost:8080/api/mem_del', vo.value)
    if (resp.data === 1) {
      alert("삭제 완료!");
    } else {
      alert("삭제 실패!");
    }
  }

  fn_clear()
  await fn_list()

}

const fn_clear = () => {
  vo.value = {m_id: "", m_name: "", tel: "", email: ""};
}
</script>
<template>
  EMP 화면

  <table>
    <thead>
    <tr>
      <td>사번</td>
      <td>이름</td>
      <td>전화</td>
      <td>이메일</td>
    </tr>
    </thead>
    <tbody>
    <tr v-for="item in list" :key="item.m_id">
      <td @click.prevent="fn_one(item.m_id)">{{ item.m_id }}</td>
      <td>{{ item.m_name }}</td>
      <td>{{ item.tel }}</td>
      <td>{{ item.email }}</td>
    </tr>
    </tbody>
  </table>
  <br/>
  <table>
    <tbody>
    <tr>
      <td>사번</td>
      <td>
        <input type="text" v-model="vo.m_id"/>
      </td>
    </tr>
    <tr>
      <td>이름</td>
      <td>
        <input type="text" v-model="vo.m_name"/>
      </td>
    </tr>
    <tr>
      <td>전화</td>
      <td>
        <input type="text" v-model="vo.tel"/>
      </td>
    </tr>
    <tr>
      <td>이메일</td>
      <td>
        <input type="text" v-model="vo.email"/>
      </td>
    </tr>
    <tr>
      <td colspan="2">
        <input type="button" value="추가" @click="fn_add()"/>
        <input type="button" value="수정" @click="fn_mod()"/>
        <input type="button" value="삭제" @click="fn_del()"/>
      </td>
    </tr>
    </tbody>
  </table>

</template>
<style>
table, tr, td {
  border: 1px solid darkolivegreen;
  text-align: center;
}

input[type='text'] {
  width: 120px;
}

a {
  color: blue;
  text-decoration: underline;
}

</style>

// he_mvvm_react/src/Mem.jsx
import React, {useEffect, useState} from 'react';
import axios from 'axios';
import './Mem.css'

function Mem() {
    let [list, setList] = useState([
        {'m_id': '1', 'm_name': '홍길동', 'tel': '010-1234-5678', 'email': 'hong@test.com'},
        {'m_id': '2', 'm_name': '김철수', 'tel': '010-2345-6789', 'email': 'kim@test.com'},
        {'m_id': '3', 'm_name': '이영희', 'tel': '010-3456-7890', 'email': 'lee@test.com'}
    ])

    let [vo, setVo] = useState({'m_id': '', 'm_name': '', 'tel': '', 'email': ''})

    useEffect(() => {
        fn_list();
    }, []);

    const fn_one = (e) => {
        console.log(e.target.dataset.m_id);
    }

    const fn_list = async () => {
        let resp = await axios.get("http://localhost:8080/mem_list.ajax");
        console.log(resp);
        let _list = resp.data.list;
        setList(_list);
    }

    const fn_add = () => {
        if (vo.m_id && vo.m_name && vo.tel && vo.email) {
            setList([...list, {...vo}]);
            setVo({'m_id': '', 'm_name': '', 'tel': '', 'email': ''});
        } else {
            alert('모든 필드를 입력해주세요.');
        }
    }

    const fn_update = () => {
        const updatedList = list.map(item =>
            item.m_id === vo.m_id ? {...vo} : item
        );
        setList(updatedList);
        setVo({'m_id': '', 'm_name': '', 'tel': '', 'email': ''});
    }

    const fn_delete = () => {
        if (vo.m_id) {
            const filteredList = list.filter(item => item.m_id !== vo.m_id);
            setList(filteredList);
            setVo({'m_id': '', 'm_name': '', 'tel': '', 'email': ''});
        } else {
            alert('삭제할 사번을 입력해주세요.');
        }
    }

    const fn_select = (selectedVo) => {
        setVo({...selectedVo});
    }

    return (
        <>
            <table>
                <thead>
                <tr>
                    <td>사번</td>
                    <td>이름</td>
                    <td>전화</td>
                    <td>이메일</td>
                </tr>
                </thead>
                <tbody>
                {list.map((vo, index) => (
                    <tr key={index}>
                        <td><a onClick={fn_one} data-m_id={vo.m_id}>{vo.m_id}</a></td>
                        <td>{vo.m_name}</td>
                        <td>{vo.tel}</td>
                        <td>{vo.email}</td>
                    </tr>
                ))}
                </tbody>
            </table>

            <table>
                <tbody>
                <tr>
                    <td>사번</td>
                    <td>
                        <input
                            type="text"
                            value={vo.m_id}
                            onChange={(e) => setVo({...vo, m_id: e.target.value})}
                        />
                    </td>
                </tr>
                <tr>
                    <td>이름</td>
                    <td>
                        <input
                            type="text"
                            value={vo.m_name}
                            onChange={(e) => setVo({...vo, m_name: e.target.value})}
                        />
                    </td>
                </tr>
                <tr>
                    <td>전화</td>
                    <td>
                        <input
                            type="text"
                            value={vo.tel}
                            onChange={(e) => setVo({...vo, tel: e.target.value})}
                        />
                    </td>
                </tr>
                <tr>
                    <td>이메일</td>
                    <td>
                        <input
                            type="text"
                            value={vo.email}
                            onChange={(e) => setVo({...vo, email: e.target.value})}
                        />
                    </td>
                </tr>
                <tr>
                    <td colSpan="2">
                        <input type="button" value="추가" onClick={fn_add}/>
                        <input type="button" value="수정" onClick={fn_update}/>
                        <input type="button" value="삭제" onClick={fn_delete}/>
                    </td>
                </tr>
                </tbody>
            </table>
        </>
    )
}

export default Mem
